### ISSUE TITLE
一点小建议🧐

### ISSUE THREAD

**Issue by Bkm016** [Rothes/ProtocolStringReplacer#10]
可否增加配置去关闭一些信息，或是使其可配置。例如：
https://github.com/Rothes/ProtocolStringReplacer/blob/708b27e04774f2ee904d3744b310a6b726fd275b/src/main/java/me/rothes/protocolstringreplacer/ProtocolStringReplacer.java#L66

https://github.com/Rothes/ProtocolStringReplacer/blob/708b27e04774f2ee904d3744b310a6b726fd275b/src/main/java/me/rothes/protocolstringreplacer/ProtocolStringReplacer.java#L69

## 我的观点

用户安装这个插件的**目的之一**可能是需要对**硬编码语言文件**进行修改，也就是说这类用户对于发送给玩家的提示信息有一定的要求和规范，这同样也包括他自身。

以及您近期在开发的 Logger 前缀替换也可能是出于这类目的。但是换作是我，我会选择用 csf 去屏蔽掉这些**有色彩**的，会吸引注意力的**废话**。

我个人非常疑惑的地方就在于 **很多插件作者** 都喜欢在控制台打印一些五颜六色的废话，例如：
* XX 插件正在加载
* XX 插件加载完成
* 当前服务端 XX 版本
* 已挂钩 XXX

不可否认 psr 是很牛逼的插件，但是您不要忽略这些小细节。

**Comment by Rothes** [comment]
感谢您提出这个议题。早期我写上服务端版本是为了方便在日志内获取用户的服务端版本，毕竟不同的版本都需要不同适配
之后就开始天花乱坠添加提示信息。
我会斟酌如何更好解决这个问题。之后主要只会发送(潜在的)错误信息。

**Comment by Bkm016** [comment]
👍

**Comment by Rothes** [comment]
在最近[语言系统的重写](https://github.com/Rothes/ProtocolStringReplacer/commit/3d3fb3e20b35197802a7eec508912f8db837bd03)中，考虑到您提出的这些信息无意义，暂决定移除这些消息.

此问题已解决，非常感谢您提出该议题和对此项目的支持，欢迎您再次反馈其他意见！
