### ISSUE TITLE
控制台全是報錯= =

### ISSUE THREAD

**Issue by WongIong** [Rothes/ProtocolStringReplacer#11]
**Describe the bug**
很多插件都會報同一個錯，zip file closed

**To Reproduce**
安裝了2.0.0版本

**Expected behavior**

**Stacktrace**
https://pastebin.com/sEffA385

**Screenshots**

**Server Informations**
 - Minecraft Version: paper 1.16.5
 - ProtocolLib Version: 470
 - ProtocolStringReplacer Version: 200

**Comment by Rothes** [comment]
尝试 更新/更换 你的服务端后再试

**Comment by WongIong** [comment]
不止是在2.0.0版, 之前的1.1.3版也有同樣的問題
在1.1.3, 其他插件或多或少可以工作. 例如DiceFurniture, 部分家具正常,但部分會明顯有位置錯誤的問題
但2.0.0就真的沒了,影響的插件全都用不了
大部分插件都好像是用protocollib作為前置的

**Comment by WongIong** [comment]
更新至1.16.5paper788最新版
一樣是持續報錯,連伺服器都進不了

但使用1.1.3版本就沒大事

**Comment by Rothes** [comment]
> 更新至1.16.5paper788最新版 一樣是持續報錯,連伺服器都進不了
> 
> 但使用1.1.3版本就沒大事

您给出的报错信息并不包含 PSR 的报错信息，但很明显这并不是 PSR 的问题。
我只能建议优先排查服务端核心(尝试使用 Airplane 核心)
因为在我的设备上无法复现，我不能提供有效的解决方式。

**Comment by WongIong** [comment]
要不我們移步DC?

**Comment by Rothes** [comment]
> 要不我們移步DC?

指的是 ”BungeeCord" 吗？由于插件前置均不支持，无法迁移

**Comment by WongIong** [comment]
Dc=discord
BC才是Bungee

**Comment by freeze-dolphin** [comment]
貌似如果配置文件写错的话有可能会报错刷屏

**Comment by WongIong** [comment]
已經解決了, 2.0.1版
