### ISSUE TITLE
Error with plugin shutting down.

### ISSUE THREAD

**Issue by Ramzie55** [Rothes/ProtocolStringReplacer#20]
**Describe the bug**
Just getting a error, which I'm not sure effects the plugin in anyway. (As I haven't add issues yet.)

**To Reproduce**
1. Use the most recent NachoSpigot jar.
2. Start the server.
3. Server should be stopped/shutdown.
4. When you begin to stop/shutdown the server, the problem will be visible in the logs.

**Expected behavior**
I haven't seen the plugin have any problems with other jars, so I'm not sure what the problem is, but hoping the error is addressed because it makes the console seem horrible.

**Stacktrace**
(https://pastebin.com/NuEymqgq)

**Screenshots**
![image](https://user-images.githubusercontent.com/54107659/147867083-f0e91b5f-b5e3-4508-a6df-6e5ae456356c.png)

**Server Informations**
 - Minecraft Version: [e.g. This server is running NachoSpigot version git-NachoSpigot-"e48db52" (MC: 1.8.8)]
 - ProtocolLib Version: [e.g. ProtocolLib v4.7.0]
 - ProtocolStringReplacer Version: [e.g. 2.3.3]
 - Plugins: [e.g. Plugins (1): ProtocolStringReplacer]

**Additional context**

**Comment by Rothes** [comment]
Fixed https://github.com/Rothes/ProtocolStringReplacer/commit/6c2e93158447405df673576f3f32ea9301693ea8
Thank you for your bug feedback
