### ISSUE TITLE
屏蔽控制台消息的时候不用空行替换

### ISSUE THREAD

**Issue by Caelvyn** [Rothes/ProtocolStringReplacer#23]
用空行替换后控制台消息是一节一节的。就像这样
![image](https://user-images.githubusercontent.com/41894399/149641240-652ef06f-71cf-450f-b95d-99b233923c70.png)

**Comment by Rothes** [comment]
请使用 Block 屏蔽控制台信息而不是 Replace 功能

**Comment by Caelvyn** [comment]
我用的是block

**Comment by Rothes** [comment]
> 我用的是block

如果使用的是高版本 Paper 服务端, Block 不要写上 Logger 和其前的文本比如 `[ProtocolStringReplacer] `,
这样 PSR 会通过 Filter 来屏蔽, 不会产生空行, 但是使用 LogPattern 屏蔽就会产生空行, 原因未知.

**Comment by Caelvyn** [comment]
我只在block下面添加了插件名字

**Comment by Rothes** [comment]
> 我只在block下面添加了插件名字

提供一下您的替换配置看看?

**Comment by Caelvyn** [comment]
[Example - 副本.txt](https://github.com/Rothes/ProtocolStringReplacer/files/7876103/Example.-.txt)

**Comment by Rothes** [comment]
> [Example - 副本.txt](https://github.com/Rothes/ProtocolStringReplacer/files/7876103/Example.-.txt)

这样就是写的是 Logger 前面的文本了, 在 Paper 1.17+ 只有写中括号后面的文本才不会导致空行.

**Comment by Caelvyn** [comment]
不好意思  不太理解您说的’写的是logger前面的文本'是什么意思

**Comment by Caelvyn** [comment]
我的是paper1.16.5

**Comment by Rothes** [comment]
> 我的是paper1.16.5

那就是我记错了- - 是 Paper 1.16+
![image](https://user-images.githubusercontent.com/47097395/149641751-ac47fedb-211c-4b4c-ad51-5135bde16660.png)
如图，蓝色框框 框住的就是我指的 Logger. 您需要写这些框框之后的文本, 例如
`无法通过远程服务器检查版本信息, 请尝试更新您的插件: java.io.IOException: Server returned HTTP response code: 502 for URL: https://raw.fastgit.org/Rothes/ProtocolStringReplacer/master/Version%20Infos.json`
`A new version of QuickShop snapshot has been released! [126]`
才能正常屏蔽.

**Comment by Caelvyn** [comment]
懂了懂了  谢谢  这就去试试

**Comment by Caelvyn** [comment]
我想把这个插件变为第一个启动会出现什么问题吗

**Comment by Rothes** [comment]
> 我想把这个插件变为第一个启动会出现什么问题吗

原理上说, 应该不会.

**Comment by Caelvyn** [comment]
好的 感谢您的付出

**Comment by Caelvyn** [comment]
插件启用顺序可以改吗  我发现加载是提前了 但是启用顺序没有

**Comment by Rothes** [comment]
> 插件启用顺序可以改吗 我发现加载是提前了 但是启用顺序没有

原理上那样做启用顺序也会更改的, 是不是把前置也写进去了? 那样控制台会有报错.

**Comment by Caelvyn** [comment]
前置没写进去  其实现在这个情况我也已经很满意了  这个插件真的很强大  spigot上有类似的但是并没有真正显著的效果  不得不佩服你的编码能力

**Comment by Rothes** [comment]
> 前置没写进去 其实现在这个情况我也已经很满意了 这个插件真的很强大 spigot上有类似的但是并没有真正显著的效果 不得不佩服你的编码能力

本来是想设计在加载的时候就读取替换配置的, 这样可以更好替换控制台信息, 后来鸽了, 就计划到 PSR 3.0.0 重写里面了.

**Comment by Caelvyn** [comment]
希望 3.0不是有生之年系列  QAQ

**Comment by Rothes** [comment]
> 希望 3.0不是有生之年系列 QAQ

实际上要修改成那样也用不了几个分钟. PSR 3.0.0 还预计要一段时间才会开工 (我还得完成一些其他的插件)
如果问题已解决, 我将关闭此议题. 需要更多交流请加入QQ群.

**Comment by Caelvyn** [comment]
好的  不过多打扰你了  感谢你的回复

**Comment by Rothes** [comment]
感谢您的支持

**Comment by Rothes** [comment]
提醒一下, 刚刚更新了 v2.5.0, 就没有我说的这个限制了. 如果使用新版本, 您可以使用原先的那个替换配置文件.
我重写了很多部分, 现在可以对所有字符进行处理.
