### ISSUE TITLE
是否支持多語言系統?

### ISSUE THREAD

**Issue by nnn950711** [Rothes/ProtocolStringReplacer#27]

**Comment by Rothes** [comment]
如果指的是 PSR 本身消息的多语言，可在 plugins\ProtocolStringReplacer\Locale 修改或添加。
如果指让修改的消息支持多语言，参考 https://rothes.gitbook.io/protocolstringreplacer/Replacer-Config/Options/Filter/User

**Comment by nnn950711** [comment]
好的謝謝。
