### ISSUE TITLE
Warns on starting and stopping server.

### ISSUE THREAD

**Issue by ghost** [Rothes/ProtocolStringReplacer#28]
**Describe the bug**
服务器开启的时候和关闭的时候插件会产生警告

**To Reproduce**
正常开关服务器

**Stacktrace**
https://pastebin.com/LC0MYHar

**Server Informations**
 - Minecraft Version: Paper version git-Paper-333 (MC: 1.18.2)
 - ProtocolLib Version: 4.8.0
 - ProtocolStringReplacer Version: 2.6.6

**Additional context**
服务器是用 MCSManager 开启的，可能没有所谓的“Terminal”？

**Comment by Rothes** [comment]
疑似 MCSManager 修改控制台内部实现, 舍弃 Reader 直接使用 stdout 导致.
已通过此提交修复: https://github.com/Rothes/ProtocolStringReplacer/commit/e0fccc02aed0895605102e55f59d5aade253a87e
