### ISSUE TITLE
Can not replace chat-type on 1.19

### ISSUE THREAD

**Issue by ghost** [Rothes/ProtocolStringReplacer#31]
**Describe the bug**
Chat 类型无法替换，不知道是插件的问题还是 ProtocolLib 改了什么。

**To Reproduce**
1. Replacers 里设置 Listen-Types: Chat
2. 在聊天里发送关键字
3. 内容未被替换并产生报错

**Expected behavior**
内容应当被替换。

**Stacktrace**
https://pastebin.com/mG0d54zC

**Server Informations**
 - Minecraft Version: git-Pufferfish-6 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b4104a6 on HEAD)
 - ProtocolLib Version: 5.0.0-SNAPSHOT-b569
 - ProtocolStringReplacer Version: 2.8.0
 - Plugins: VentureChat, CMI

**Comment by juzijun233** [comment]
你在bungee上有VentureChat吗？

**Comment by Rothes** [comment]
初步确定为 Spigot 的 Bungee-Chat API 的问题，未能正常处理一些特殊的（可能不合规范的） JSON。

**Comment by Rothes** [comment]
临时解决方案：尝试在Json替换中将`"action":"",`替换为空白，这样可以让其正确解析Common替换。
