### ISSUE TITLE
Something wrong on cat

### ISSUE THREAD

**Issue by ghost** [Rothes/ProtocolStringReplacer#32]
**Describe the bug**
Well, I didn't known why this happened, after deleting plugins used ProtocolLib as dependency one by one, I found that maybe ProtocolStringReplacer causes this problem.

**To Reproduce**
1. Install ProtocolLib and ProtocolStringReplacer.
2. In overworld, summoning a cat. 
3. See error. If not, restarting the server and try again.

**Stacktrace**
https://pastebin.com/viTwY8TM

**Server Informations**
 - Minecraft Version: 1.19 (git-Paper-34)
 - ProtocolLib Version: v5.0.0-SNAPSHOT-b569
 - ProtocolStringReplacer Version: 2.8.0
 - Plugins: PlaceholderAPI, ProtocolLib, ProtocolStringReplacer (no more plugins)

**Comment by Rothes** [comment]
Bug from ProtocolLib, please report to them...
https://github.com/dmulloy2/ProtocolLib/issues
