### ISSUE TITLE
希望为me.rothes.protocolstringreplacer.replacer.ReplacerConfig提供一个抽象的接口

### ISSUE THREAD

**Issue by 4o4E** [Rothes/ProtocolStringReplacer#33]
我计划写一个附属插件，提供的配置并不存在文件

我设想的解决方案

1. 允许直接通过String构造ReplacerConfig
2. 为me.rothes.protocolstringreplacer.replacer.ReplacerConfig抽象一个接口，允许自己实现

**Comment by Rothes** [comment]
https://github.com/Rothes/ProtocolStringReplacer/commit/d6ef1179ff5d545d76d51d3b66b0ab1aa7eb44cf#diff-3900199bd4eb4252268857835006ce44d3ed74d1f3ee74acedc0a16251f610a8
尚不支持使用`/psr file`指令修改ReplacerConfig配置

**Comment by Rothes** [comment]
将于几天后发布PSR v2.11.0 . 如还有其它必要的API更改, 请及时提出.

**Comment by 4o4E** [comment]
> 将于几天后发布PSR v2.11.0 . 如还有其它必要的API更改, 请及时提出.

希望增加一个reload的事件，或者可以添加runnable在重载后调用，以便在重载后添加配置

**Comment by Rothes** [comment]
已添加 PsrReloadEvent https://github.com/Rothes/ProtocolStringReplacer/commit/b66eaae695d241a9d1a54744d27e39ba50228196
