### ISSUE TITLE
导致无法显示BetonQuest任务NPC对话选项

### ISSUE THREAD

**Issue by RusBrook** [Rothes/ProtocolStringReplacer#34]
**Describe the bug**
ProtocolStringReplacer和BetonQuest2.0.0开发板的聊天冲突
(无法显示NPC的对话,取消对话后对话选项才出现)
服务端版本1.18.2
ProtocolStringReplacer版本 2.12.2
BetonQuest版本2.0.0-DEV-461
[BetonQuest地址:](https://dev.betonquest.org)

**Comment by Rothes** [comment]
请提供视频或截图，经检查BetonQuest使用Spigot/Bungee Chat API发送聊天信息，应该能被正常处理。

**Comment by RusBrook** [comment]
老版本的BetonQuest没有问题测试了
BetonQuest 1.12.9 没出现这个问题
BetonQuest 2.0.0-DEV-461 出现了这个问题
试了几个BetonQuest的开发板都是有这个问题
这个是BetonQuest 2.0.0的地址 https://dev.betonquest.org/

https://user-images.githubusercontent.com/44542189/205361011-09ccccfa-62bf-4c29-a5eb-e0a4fa9c327c.mp4



> 请提供视频或截图，检查BetonQuest使用Spigot/Bungee Chat API发送聊天消息，应该能够被正常处理。

**Comment by Rothes** [comment]
未能复现
git-Paper-327 (MC: 1.19.3)
BetonQuest 2.0.30 b2809

**Comment by Rothes** [comment]
Closed due to no response. Please reopen if the issue still exists.
