### ISSUE TITLE
Mohist1.12 无法正常使用 附报错

### ISSUE THREAD

**Issue by KanyShigure** [Rothes/ProtocolStringReplacer#37]
核心版本Mohist1.12，PSR最新构建版
安装PSR后，热重载会使服务器软死机，未有相关报错
而服务器完全重载后，玩家进入服务器时自动被踢，客户端反馈Internl server error[相关报错链接](https://pastes.dev/9I8PZyYimS)

附1：以及，似乎产生了较为严重的性能问题，完全重启的过程中主线程被阻塞了至少一分钟

**Comment by Rothes** [comment]
ProtocolLib 不支持 Mohist 服务端，请考虑更换 CatServer

**Comment by KanyShigure** [comment]
> ProtocolLib 不支持 Mohist 服务端，请考虑更换 CatServer

好的，但碍于其他插件不支持Cat，先考虑一下
