### ISSUE TITLE
无法在告示牌上用上颜色代码

### ISSUE THREAD

**Issue by nnn950711** [Rothes/ProtocolStringReplacer#4]
**Describe the bug**
我无法在告示牌上用上颜色代码，显示出来的颜色都是黑色或者白色，这算是Bug吗?

**Screenshots**
![2021-07-16_15 24 32](https://user-images.githubusercontent.com/41001774/125909004-99402a37-ee69-458a-bb58-1114c03a27d6.png)
![2021-07-16_15 24 36](https://user-images.githubusercontent.com/41001774/125909080-0d1b664b-f37a-4453-8b20-f6f8c5a8474e.png)

**Server Informations**
 - Minecraft Version: git-Purpur-1270 (MC: 1.17.1)
 - ProtocolLib Version: ProtocolLib-4.7.0
 - ProtocolStringReplacer Version: ProtocolStringReplacer v1.3.3.1

**Comment by Rothes** [comment]
待测试.

**Comment by Rothes** [comment]
插件并不自带转换游戏内玩家的&彩色符号功能。
我就假设反馈的问题是其他插件已经转换了彩色符号，然后本插件把牌子上原有的彩色符号移除了。

**Comment by nnn950711** [comment]
问一个问题:　能够支援　Triton　的占位符吗?

**Comment by Rothes** [comment]
> 问一个问题:　能够支援　Triton　的占位符吗?

只要是PlaceholderAPI的占位符 都能用。

-- 此问题已确认。

**Comment by Rothes** [comment]
此问题已修复. 请在MCBBS上更新v1.3.4.
