### ISSUE TITLE
[Bug] 1.8.8默认配置加载失败

### ISSUE THREAD

**Issue by Coquettishpig** [Rothes/ProtocolStringReplacer#43]
### 检查清单

- [X] 我已经尝试过了最新开发版本的 ProtocolLib.
- [X] 我正在使用最新的官方 PSR.
- [X] 我搜寻了类似的未关闭议题, 但没有找到任何有关的错误报告。

### 描述

![image](https://github.com/Rothes/ProtocolStringReplacer/assets/107100449/ba2c6852-12dd-4fbd-a6d6-e52e3fe50962)

### 重现步骤

1.8.8启动服务器，加载插件

### 预期行为

应该正确加载

### 堆栈轨迹

无

### 服务端版本

git-Spigot-21fe707-e1ebe52

### ProtocolStringReplacer 版本

2.19.0

### ProtocolLib 版本

ProtocolLib v5.1.0-SNAPSHOT-653

**Comment by Coquettishpig** [comment]
![image](https://github.com/Rothes/ProtocolStringReplacer/assets/107100449/cc05f5d4-800d-45a0-88a8-7e3d176b23ee)

**Comment by Rothes** [comment]
Fixed on https://github.com/Rothes/ProtocolStringReplacer/commit/0ae1c5a8db0c2c621c678ae61ee92bdefa7d2018
