### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Coquettishpig** [Rothes/ProtocolStringReplacer#44]
### 检查清单

- [X] 我已经尝试过了最新开发版本的 ProtocolLib.
- [X] 我正在使用最新的官方 PSR.
- [X] 我搜寻了类似的未关闭议题, 但没有找到任何有关的错误报告。

### 描述

![image](https://github.com/Rothes/ProtocolStringReplacer/assets/107100449/df2e7d6d-6d1d-46d3-af69-eb02b472ed88)
最新构建还是一样

### 重现步骤

1.8.8加载插件

### 预期行为

正常运行

### 堆栈轨迹

暂无

### 服务端版本

git-Spigot-21fe707-e1ebe52

### ProtocolStringReplacer 版本

2.19.0

### ProtocolLib 版本

5.0.0-SNAPSHOT-b606

**Comment by Rothes** [comment]
你确定你是最新构建吗？

**Comment by Coquettishpig** [comment]
> 你确定你是最新构建吗？

昨天下午六点拉取构建的

**Comment by Rothes** [comment]
你可以直接在Actions里面下载构建

**Comment by Coquettishpig** [comment]
> 你可以直接在Actions里面下载构建

没问题了

**Comment by Coquettishpig** [comment]
> 你可以直接在Actions里面下载构建

thanks
