### ISSUE TITLE
[Bug] PlayerChat packet handle may not work

### ISSUE THREAD

**Issue by Coquettishpig** [Rothes/ProtocolStringReplacer#45]
### 检查清单

- [X] 我已经尝试过了最新开发版本的 ProtocolLib.
- [X] 我正在使用最新的官方 PSR.
- [X] 我搜寻了类似的未关闭议题, 但没有找到任何有关的错误报告。

### 描述

<img width="464" alt="73e69ad2621221fb5320d8475f62faaa" src="https://github.com/Rothes/ProtocolStringReplacer/assets/107100449/232934e2-1033-4a46-af24-ce48c9e9c15f">

### 重现步骤

1.8.8启动应该就能复现了

### 预期行为

应该不会出现问题

### 服务端版本

git-PandaSpigot-116 (MC: 1.8.8)

### ProtocolStringReplacer 版本

2.19.3

### ProtocolLib 版本

v5.2.0-SNAPSHOT-679

**Comment by Coquettishpig** [comment]
补充：2.19.3试过和2.19.2一样

**Comment by Rothes** [comment]
https://github.com/Rothes/ProtocolStringReplacer/commit/72fd444c78c17773d3611d082b388f9f0bfa9888
