### ISSUE TITLE
[Bug] 在1.21中会导致物品堆叠出现显示问题

### ISSUE THREAD

**Issue by duckkingg** [Rothes/ProtocolStringReplacer#49]
### 检查清单

- [X] 我已经尝试过了最新开发版本的 ProtocolLib.
- [X] 我正在使用最新的官方 PSR.
- [X] 我搜寻了类似的未关闭议题, 但没有找到任何有关的错误报告。

### 描述

在1.21中会导致物品堆叠出现显示问题，实际数量没有问题，只是显示不正常.使用起来异常的难受，麻烦大哥尽快修复

### 重现步骤

-

### 预期行为

-

### 服务端版本

purpur-2280

### ProtocolStringReplacer 版本

3.0，3.01

### ProtocolLib 版本

ProtocolLib v5.3.0-SNAPSHOT-721，5.3.0-SNAPSHOT-726

**Comment by Rothes** [comment]
最新构建已修复，请下载开发版本。
