### ISSUE TITLE
[Bug] 1.21.1注册事件异常

### ISSUE THREAD

**Issue by NeglectDream** [Rothes/ProtocolStringReplacer#50]
### 检查清单

- [X] 我已经尝试过了最新开发版本的 ProtocolLib.
- [X] 我正在使用最新的官方 PSR.
- [X] 我搜寻了类似的未关闭议题, 但没有找到任何有关的错误报告。

### 描述

我创建了一个chat检测的消息屏蔽

### 重现步骤

开服即报错

### 预期行为

没报错

### 堆栈轨迹

https://pastebin.com/qdHZVPFH

### 服务端版本

Purpur-1.21.1

### ProtocolStringReplacer 版本

3.0.2

### ProtocolLib 版本

5.3.0-SNAPSHOT-726

**Comment by CuteLittleSky** [comment]
遇到了相同问题
