### ISSUE TITLE
某些时候物品丢在地板上不会显示

### ISSUE THREAD

**Issue by nnn950711** [Rothes/ProtocolStringReplacer#7]
**Describe the bug**
物品丢在地板上不会显示 (尤其是对於插件的物品)

后台没有报错
没有安装 高清修复

**Screenshots**

https://user-images.githubusercontent.com/41001774/126085584-03131958-6939-4e18-b23d-d8683ac17e61.mp4

**Server Informations**
 - Minecraft Version: git-Purpur-1285 (MC: 1.17.1)
 - ProtocolLib Version: ProtocolLib-4.7.0
 - ProtocolStringReplacer Version: ProtocolStringReplacer v1.4.1

**Comment by Rothes** [comment]
看起来可能是由于 #6 同样的问题导致。请尝试使用ProtocolLib开发版本并等待他们修复那个报错。

**Comment by Rothes** [comment]
能否说明您的掉落物名称全息显示插件以及版本？

**Comment by Rothes** [comment]
据我所知，此问题已有人在ProtocolLib上反馈。
https://github.com/dmulloy2/ProtocolLib/issues/1337

**Comment by nnn950711** [comment]
> 能否说明您的掉落物名称全息显示插件以及版本？
HolographicDisplays v2.4.8

**Comment by nnn950711** [comment]
> 看起来可能是由于 #6 同样的问题导致。请尝试使用ProtocolLib开发版本并等待他们修复那个报错。
开发版目前是 4.7.0 都是最新的

**Comment by nnn950711** [comment]
> > 能否说明您的掉落物名称全息显示插件以及版本？
> > InteractionVisualizer-1.16.3.0

**Comment by Rothes** [comment]
由于此为 ProtocolLib 导致的问题，故关闭此议题。下个版本会添加一个配置处理。

**Comment by Rothes** [comment]
已在 Config.yml 添加配置来临时解决此问题. 待 ProtocolLib 解决该问题后将移除此配置.
